version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "06:00"
      timezone: "Etc/UTC"
    ignore:
      - dependency-name: "org.cryptomator:integrations-api"
        versions: [ "2.0.0-alpha1" ]
    groups:
      maven-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/" # even for `.github/workflows`
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"